ONLYOFFICE-QA/testing-wrata

- Changelog.md
- docker-compose.yml
Since recent release of all version of postgresql (9, 10, 11)
starting `docker-compose up db` on empty machine will cause
error about specifying password or adding trust method.
Since this db is only acceseble through docker network it's
save not to use password
See for more details:
https://github.com/docker-library/postgres/issues/681
> Fix docker-compose with actual version of postgresql

- Changelog.md
- app/models/start_option.rb
- app/server/managers/history_manager.rb
- app/views/application/_history_entry.html.erb
- db/migrate/20200420085308_remove_deprecated_branch_from_start_options.rb
- db/schema.rb
Those projects not longer used
So no need to store branch info for them, or any other info
> Remove deprecated projects

- Changelog.md
- app/views/clients/api_keys.html.erb
If folder not exist - old command just failed
Create folder for key before
> Fix `/clinets/api_keys` command if key folder not exists

- app/assets/stylesheets/serverHistory.css.scss
> Fix some more css for history table

- Changelog.md
- app/models/concerns/server_test_out.rb
Server restart on error like this:
```
[1mTraceback[m (most recent call last):
7: from /root/wrata/app/server/managers/thread_manager.rb:6:in `block in create_main_thread'
6: from /root/wrata/app/server/managers/thread_manager.rb:6:in `loop'
5: from /root/wrata/app/server/managers/thread_manager.rb:16:in `block (2 levels) in create_main_thread'
4: from /root/wrata/app/server/managers/history_manager.rb:18:in `add_data_to_history'
3: from /root/wrata/app/server/managers/history_manager.rb:27:in `save_run_history_in_db'
2: from /root/wrata/app/models/concerns/server_test_out.rb:28:in `final_result_html'
1: from /root/wrata/app/models/concerns/server_test_out.rb:28:in `match'
/root/wrata/app/models/concerns/server_test_out.rb:28:in `match': [1minvalid byte sequence in UTF-8 …
```
> Fix server restart on `ArgumentError`

- Changelog.md
- app/server/managers/test_manager.rb
For some reason in `testing-onlyoffice` project
watir 6.14.0 installed by default, but not the latest
6.17.0
This is not actual problem, but just a result of it
In that scenario rspec command cannot find some gems
and raise errors like those:
```
/root/RubymineProjects/TeamLab/Framework/TestInstance.rb:1:in `require': cannot load such file -- headless (LoadError)
```
But headless gem is installed
> Fix calling rspec command in gems are outdated

- CHANGELOG.md
- app/models/start_option.rb
There is error in full log of test if test is started on
custom portal, for example `https://nacho.teamlab.info`
```
sed: -e expression #1, char 65: unknown option to `s'
```
> Fix `sed` error for test start script for custom service url

- CHANGELOG.md
- config/environments/production.rb
This allow shorten logs to analyze in case of failure
But may contain some unknown side-effects, like missing
real problems in log
Try to use it for now, but revert in future if some errors
will go unnoticed
> Reduce production log level to `:warn`

- CHANGELOG.md
- Gemfile
> Split `test` and `development` gem groups

- CHANGELOG.md
- app/server/managers/test_manager.rb
Fix #990
Before this change - there is no way to check via env variable
is it `com us` or `com eu`, just `com` in `SPEC_REGION`
> Send full region string (like `com us`) in `SPEC_REGION` env

- CHANGELOG.md
- app/workers/delayed_run_manager.rb
Method was removed by mistake [here](https://github.com/ONLYOFFICE/testing-wrata/pull/612)
Error look liked this:
```
undefined method `update' for #, #, #, #, #, #, #, #, #, #]>, @run_scan_thread=#>
```
> Fix broken `DelayRun` change time methods

- CHANGELOG.md
- app/assets/stylesheets/apiKeys.css.scss
- app/views/clients/api_keys.html.erb
It's quite hard to allow copying of this command
But current code allow safe selection of this command
> Fix ApiKeys command on Firefox

- CHANGELOG.md
- Dockerfile
- docker-compose.yml
This reduce image size by 44% by 349 mb
```
$ docker images
REPOSITORY   TAG            IMAGE ID       CREATED         SIZE
ubuntu       latest         07651960da8c   5 seconds ago   1.13GB
alpine       latest         ba0d9ecc2d1c   3 minutes ago   781MB
```
> Use `alpine` as base image for app

- CHANGELOG.md
- app/controllers/concerns/server_thread_methods/html_result_manager.rb
Program crashed with something like this in logs:
```
/usr/local/lib/ruby/3.0.0/net/protocol.rb:227:in `rbuf_fill': ^[[1mend of file reached (^[[1;4mEOFError^[[m^[[1m)^[[m
from /usr/local/lib/ruby/3.0.0/net/protocol.rb:193:in `readuntil'
from /usr/local/lib/ruby/3.0.0/net/protocol.rb:203:in `readline'
from /usr/local/lib/ruby/3.0.0/net/http/response.rb:42:in `read_status_line'
from /usr/local/lib/ruby/3.0.0/net/http/response.rb:31:in `read_new'
from /usr/local/lib/ruby/3.0.0/net/http.rb:1557:in `block in transport_request'
from /usr/local/lib/ruby/3.0.0/net/http.rb:1548:in `catch'
from /usr/local/lib/ruby/3.0.0/net/http.rb:1548:in `transport_request'
from /usr/local/lib/ruby/3.0.0/net/http.rb:1521:in `request'
from /usr/local/lib/ruby/3.0.0/net/http.rb:1514:in `block in request'
from …
```
> Fix failure when `EOFError` happened during html result read

- .github/workflows/check.yml
It was installing v3.1 instead of v3.0
See https://github.com/ruby/setup-ruby/issues/252 for more details
> Clarify ruby version

- CHANGELOG.md
- config/application.rb
- config/environments/test.rb
- config/initializers/managers.rb
This is needed in rails v7 because it's default now
> Migrate autoloader to `:zeitwerk`

- .github/workflows/check.yml
- CHANGELOG.md
Without it latest version of `markdownlint-cli` is failing
> Actualize `nodejs` version in CI

- CHANGELOG.md
- app/javascript/packs/application.js
- app/javascript/src/main.js
- package.json
- yarn.lock
Without this lib all DELETE requests result in CSRF verification error
Because this lib add it's verification by default
So explicit line is not needed any more
> Fix almost all non-GET/POST request with require of `jquery-ujs`

- CHANGELOG.md
- app/assets/stylesheets/style.css.scss
Should fix situation like this:
> Fix language bar position on 1366x768 screen

- CHANGELOG.md
- Dockerfile
For some time bundle by itself knows which version to install, fetching this info from Gemfile.lock
> Remove extra docker step to install bundler

- CHANGELOG.md
- Dockerfile
Possible fix for https://github.com/ONLYOFFICE/testing-wrata/issues/2103
Broken in https://github.com/ONLYOFFICE/testing-wrata/pull/1825
> Fix missing `public/pack` directory in Docker image

- CHANGELOG.md
- Dockerfile
```
$ docker build .
[+] Building 1.1s (3/3) FINISHED                                                                                                                                              docker:default
=> [internal] load build definition from Dockerfile                                                                                                                                    0.0s
=> => transferring dockerfile: 1.12kB                                                                                                                                                  0.0s
=> WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 1) 
```
> Fix warning for `docker build` about case of `AS` statement

- CHANGELOG.md
- docker-compose.yml
```
$ docker compose up
WARN[0000] /testing-wrata/docker-compose.yml: `version` is obsolete 
```
> Remove obsolete `version` field from `docker-compose.yml`
